[package]
name = "minmaxheap"
version = "0.1.0"
authors = ["dchoi"]
edition = "2018"
description = "Binary heap implementatino in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
